repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  # - id: no-commit-to-branch
  - id: mixed-line-ending
    args: [--fix, lf]
- repo: https://github.com/google/yamlfmt
  rev: v0.11.0
  hooks:
  - id: yamlfmt
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [-c, .yamllint.yaml]
# Linter not working with TinyGO
# - repo: https://github.com/golangci/golangci-lint
#   rev: v1.57.2
#   hooks:
#   - id: golangci-lint
